# Generated by Django 3.1.2 on 2020-10-08 22:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
                ('posted_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
