# Generated by Django 3.1.2 on 2020-10-08 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification', '0001_initial'),
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='tweet_notify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweet.tweets'),
        ),
    ]
